// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4cdAONwi2ViT3FtL9vQylKAbMar0ooH8',
    appId: '1:834623682294:web:4ed52a56926e9dbf7f1ed7',
    messagingSenderId: '834623682294',
    projectId: 'ttime-91668',
    authDomain: 'ttime-91668.firebaseapp.com',
    storageBucket: 'ttime-91668.firebasestorage.app',
    measurementId: 'G-3TFQ512Y5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJOOl5dsEiXJ3jyh5hHWxvJOfKSGsKroQ',
    appId: '1:834623682294:android:6db3c9e98a4a9f657f1ed7',
    messagingSenderId: '834623682294',
    projectId: 'ttime-91668',
    storageBucket: 'ttime-91668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWvLjKg_5z14TzxynI4Rf8L6rRjcN2RVE',
    appId: '1:834623682294:ios:39a0e76767357a4e7f1ed7',
    messagingSenderId: '834623682294',
    projectId: 'ttime-91668',
    storageBucket: 'ttime-91668.firebasestorage.app',
    iosBundleId: 'com.example.aa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4cdAONwi2ViT3FtL9vQylKAbMar0ooH8',
    appId: '1:834623682294:web:dccc4c9fab738d037f1ed7',
    messagingSenderId: '834623682294',
    projectId: 'ttime-91668',
    authDomain: 'ttime-91668.firebaseapp.com',
    storageBucket: 'ttime-91668.firebasestorage.app',
    measurementId: 'G-2SLSCK5L6Z',
  );
}
